### ISSUE TITLE
Support for Github Theme URI

### ISSUE THREAD

**Issue by xavierroy** [dshanske/iw26#10]
It would be great if you could add a GitHUB URI as in ZenPress:
https://github.com/pfefferle/ZenPress/blob/1888fa6af9816c207258c6a692356430c6bfbdba/style.css#L13

Makes it easier to pull the theme using the GitHub Updater plugin (https://github.com/afragen/github-updater).

**Comment by dshanske** [comment]
Resolved. Sorry I missed this for a bit.
